# ------------------------------------------------------------
# GitHub Action to Deploy the DNet Bot to an Azure Environment
# ------------------------------------------------------------
# 
# Modify the Environment Variables below if you want to change
# any of the default values, otherwise the following secrets
# need to be set to ensure the GitHub actions can connect and
# build into your Azure tenancy:
#
# AZURE_CREDENTIALS - The Service Principle details for Azure
# SUBSCRIPTION_ID - Your Subscription ID

# name: TestAndTroubleshootFlow
